// Icon names are present in installed @fortawesome/fontawesome-free 6.7.2.
// Render as `fa-solid fa-${icon}`. Keep this metadata separate from existing prices.
export const mentoringDetails: Record<string, readonly [string, string]> = {
  ai: ['robot', 'Use practical AI tools to save time and solve everyday business problems.'],
  design: ['palette', 'Build design skills for clearer, more engaging digital experiences.'],
  business: ['briefcase', 'Turn business ideas into practical plans and confident next steps.'],
  development: ['code', 'Learn to build, improve, and maintain useful websites and applications.'],
  'resume-review': ['file-lines', 'Present your experience clearly so the right opportunities find you.'],
  'career-advice': ['compass', 'Choose a direction and build a realistic plan for your next opportunity.'],
  'gamify-learning': ['gamepad', 'Make learning more engaging with challenges, feedback, and progress.'],
  'project-management': ['list-check', 'Organize work, set priorities, and keep your team moving together.'],
  'computers-technology': ['computer', 'Get comfortable with the technology your work depends on.'],
  'technical-writing-reading': ['book-open', 'Explain technical ideas clearly and understand complex documentation.'],
};

export const marketingDetails: Record<string, readonly [string, string]> = {
  seo: ['magnifying-glass', 'Help customers discover your website through relevant searches.'],
  cms: ['database', 'Keep your website content fresh with an easier publishing workflow.'],
  automations: ['gears', 'Connect repetitive tasks so your team can focus on customers.'],
  advertising: ['bullhorn', 'Reach relevant audiences with focused campaigns and clear messaging.'],
  'social-media': ['share-nodes', 'Build an active social presence that keeps your business visible.'],
  'ai-drone-analysis': ['satellite-dish', 'Turn aerial footage and data into useful business insights.'],
  'customer-feedback': ['comments', 'Learn what customers need and uncover opportunities to improve.'],
  'photography-videography': ['camera', 'Show your products, spaces, and story with compelling visual content.'],
  'graphic-design-custom-art': ['palette', 'Create distinctive visuals that make your brand easier to recognize.'],
  'writing-copy-articles-blogs': ['pen-nib', 'Explain your value with clear copy, useful articles, and engaging stories.'],
  'short-form-video': ['clapperboard', 'Capture attention with short videos made for social feeds.'],
};

export const buildDetails: Record<string, readonly [string, string]> = {
  blog: ['blog', 'Share expertise and give visitors a reason to return.'],
  qr: ['qrcode', 'Connect printed materials directly to your digital experience.'],
  'to-do': ['list-check', 'Help users organize tasks and keep track of progress.'],
  grids: ['table-cells', 'Make products, projects, or information easier to browse.'],
  charts: ['chart-column', 'Turn numbers into clear visual comparisons.'],
  stocks: ['arrow-trend-up', 'Bring market information into your website or dashboard.'],
  search: ['magnifying-glass', 'Help visitors find the content or products they need.'],
  testing: ['vial', 'Check key interactions so customers can use them with confidence.'],
  reviews: ['star', 'Build trust by making customer experiences visible.'],
  sliders: ['images', 'Showcase several products or highlights in a compact space.'],
  logo: ['pen-nib', 'Give your business a recognizable visual signature.'],
  security: ['shield-halved', 'Strengthen safeguards around your website and user information.'],
  news: ['newspaper', 'Keep visitors informed with timely articles and updates.'],
  media: ['circle-play', 'Let visitors watch or listen without leaving your site.'],
  clock: ['clock', 'Display live time where schedules or global teams need it.'],
  loader: ['spinner', 'Give users clear feedback while content is loading.'],
  design: ['swatchbook', 'Explore a visual direction before building the full experience.'],
  'ai-chatbot': ['robot', 'Help visitors find answers and take their next step.'],
  maps: ['location-dot', 'Make business locations and directions easy to find.'],
  'drag-drop': ['hand-pointer', 'Make arranging content or uploading files feel intuitive.'],
  weather: ['cloud-sun', 'Show useful local conditions for planning and travel.'],
  maintenance: ['screwdriver-wrench', 'Keep your digital experience current as business needs change.'],
  content: ['file-lines', 'Give each page clear, useful words that explain your value.'],
  music: ['music', 'Bring music into an experience that suits your brand.'],
  haptics: ['hand', 'Reinforce mobile interactions with subtle touch feedback.'],
  automations: ['gears', 'Reduce manual work by connecting routine actions.'],
  'api-server': ['server', 'Connect your application to data and the services it needs.'],
  functions: ['cloud', 'Run useful background actions without extra user effort.'],
  location: ['location-crosshairs', 'Offer location-aware features and relevant nearby information.'],
  analytics: ['chart-line', 'See how visitors use your site and where interest grows.'],
  audio: ['wave-square', 'Make audio content more engaging with responsive visuals.'],
  dashboard: ['gauge-high', 'Bring key information and everyday actions into one view.'],
  announcements: ['bullhorn', 'Keep important news and offers easy to notice.'],
  international: ['globe', 'Make your experience more useful to audiences across regions.'],
  accessibility: ['universal-access', 'Help more people navigate and use your experience.'],
  pwa: ['mobile-screen-button', 'Give your website a more convenient, app-like experience.'],
  fonts: ['font', 'Express your brand with distinctive, readable typography.'],
  themes: ['circle-half-stroke', 'Let visitors choose a comfortable light or dark appearance.'],
  'contact-form': ['envelope', 'Give potential customers an easy way to get in touch.'],
  'adv-analytics': ['chart-pie', 'Explore deeper activity patterns to guide business decisions.'],
  capture: ['comments', 'Collect feedback where customers already interact with you.'],
  storage: ['cloud-arrow-up', 'Let users upload and access the files they need.'],
  missed: ['phone-volume', 'Follow up on missed calls so potential leads stay connected.'],
  images: ['photo-film', 'Show visitors what you offer through useful visual examples.'],
  email: ['at', 'Present a professional identity with an email address on your domain.'],
  'social-media': ['share-nodes', 'Connect visitors to your social content and community.'],
  animations: ['wand-magic-sparkles', 'Guide attention with subtle movement and interaction feedback.'],
  'cms-database': ['database', 'Organize your content and data for easier everyday updates.'],
  'advanced-contact-form': ['file-circle-plus', 'Collect detailed requests so your team can respond more effectively.'],
  'adv-animations': ['wand-magic-sparkles', 'Create expressive motion that brings your brand experience to life.'],
  'booking-calendar': ['calendar-days', 'Help customers choose a time and book your services.'],
  'customer-order-tracking': ['truck-fast', 'Keep customers informed about the progress of their orders.'],
  'news-letter': ['rss', 'Keep your audience connected with ongoing updates.'],
  multiplayer: ['users', 'Let people play or participate together in shared experiences.'],
  notifications: ['bell', 'Keep users informed with relevant updates and messages.'],
  auth: ['user-shield', 'Give users personal accounts with appropriate access and permissions.'],
  ecommerce: ['cart-shopping', 'Let customers browse, buy, subscribe, and pay online.'],
};

