import { Roles } from '../types/types';
import type { NavItem, PageCopy, Service, Skill, SocialLink, Stat, TopBarItem } from '@/shared/types/app';

export const config = {
  title: `Piratechs`,
  domain: `piratechs.com`,
  contactEmail: `info@piratechs.com`,
  description: `Built with Next, TypeScript, and GSAP`,
  nav: [
    { id: `home`, label: `Home`, href: `/`, icon: `fa-solid fa-house` },
    { id: `about`, label: `About`, href: `/about`, icon: `fa-solid fa-anchor` },
    { id: `projects`, label: `Projects`, href: `/projects`, icon: `fa-solid fa-diagram-project` },
    { id: `services`, label: `Services`, href: `/services`, icon: `fa-solid fa-layer-group` },
    { id: `store`, label: `Store`, href: `/store`, icon: `fa-solid fa-store`, role: Roles.Editor },
    { id: `features`, label: `Features`, href: `/features`, icon: `fa-solid fa-list-check`, role: Roles.Editor },
    { id: `gallery`, label: `Gallery`, href: `/gallery`, icon: `fa-solid fa-images`, role: Roles.Editor },
    { id: `contact`, label: `Contact`, href: `/contact`, icon: `fa-solid fa-paper-plane` },
  ] satisfies NavItem[],
  nav_playground: [
    { id: `home`, label: `Home`, href: `/playground`, icon: `fa-solid fa-house` },
    { id: `sandbox`, label: `Sandbox`, href: `/sandbox`, icon: `fa-solid fa-anchor` },
  ] satisfies NavItem[],
  topBarItems: [
    { icon: `fa-solid fa-code`, label: `Stack`, text: `TypeScript + Sass + Next` },
    { icon: `fa-solid fa-database`, label: `Data`, text: `Python, JSON, SQL, and REST APIs` },
    { icon: `fa-solid fa-briefcase`, label: `Experience`, text: `4+ years software engineering at Mitsubishi Electric` },
    { icon: `fa-solid fa-mobile-screen-button`, label: `PWA`, text: `Responsive web and installable app direction` },
    { icon: `fa-brands fa-wordpress`, label: `CMS`, text: `WordPress restorations, CMS builds, and portfolio sites` },
    { icon: `fa-brands fa-github`, label: `Projects`, text: `Live deployments and source-backed proof of work` },
    { icon: `fa-solid fa-fire-flame-curved`, label: `Firebase`, text: `Auth-ready app shell for future database features` },
    { icon: `fa-solid fa-layer-group`, label: `Services`, text: `Front-end polish backed by full-stack delivery` },
  ] satisfies TopBarItem[],
  pages: {
    home: {
      eyebrow: `Piratechs`,
      title: `Design // Develop Full-Stack Applications`,
      summary: `Full-Stack Design // Development Agency Portfolio Built with Next, TypeScript, and GSAP`,
      html: `Design <span class="slashes">//</span> Develop<br> Full<span class="slashes">-</span>Stack<br> Applications`,
      // summaryHtml: `Full<span class="slashes">-</span>Stack Design <span class="slashes">//</span> Development Agency Portfolio Built with Next, TypeScript, GSAP, etc<span class="slashes">.</span>`,
    },
    about: {
      eyebrow: `About`,
      title: `Here's a Bit About // What Anchors Us`,
      html: `Here<span class="slashes">'</span>s a Bit About <span class="slashes">//</span><br> What Anchors Us`,
      summary: `One stop shop for all your digital needs, for any application your business may require.`,
      // summaryHtml: `One stop shop for all your digital needs<span class="slashes">,</span> whether they be apps<span class="slashes">,</span> games<span class="slashes">,</span> websites<span class="slashes">,</span> and so much more<span class="slashes">!</span>`,
    },
    projects: {
      eyebrow: `Projects`,
      title: `Experience // Showcase`,
      html: `Experience <span class="slashes">//</span><br> Showcase`,
      summary: `Here are some of the projects and the work that we are proud of, as well as what made each project unique.`,
    },
    services: {
      eyebrow: `Services`,
      title: `Elegant Design // Enterprise Performance`,
      html: `Elegant Design <span class="slashes">//</span><br> Enterprise Performance`,
      summary: `Data-driven apps, automation, integrations, and branded product systems with practical delivery in mind.`,
    },
    store: {
      eyebrow: `Store`,
      title: `A future shelf for digital tools`,
      summary: `A scalable route for templates, small utilities, downloadable assets, and productized Piratechs experiments when the app grows past portfolio mode.`,
    },
    features: {
      eyebrow: `Features`,
      title: `Fast, installable, responsive, and easy to expand`,
      summary: `The Next foundation gives Piratechs clean routes, PWA behavior, reusable sections, API routes, and a future Firebase-backed data layer.`,
    },
    gallery: {
      eyebrow: `Gallery`,
      title: `A visual archive for apps, brands, and experiments`,
      summary: `A showcase route for screenshots, logos, WordPress work, interface studies, game projects, and future portfolio media.`,
    },
    contact: {
      eyebrow: `Contact`,
      title: `Get In Touch // Reach Out`,
      html: `Get In Touch <span class="slashes">//</span><br> Reach Out`,
      summary: `Send us an inquiry with your questions so we can learn better about your business and needs.`,
    },
  } satisfies Record<string, PageCopy>,
  stats: [
    { 
      value: `10+`, 
      title: `Years`,
      label: `Years of Experience`, 
      text: `Full-Stack Design // Development`, 
      html: `Full<span class="slashes slashesSM">-</span>Stack Design <span class="slashes slashesSM">//</span> Development`, 
    },
    { label: `Technologies`, value: `100+`, text:  `PWAs, Apps, E-Commerce, Games, APIs` },
    { label: `Applications`, value: `1000+`, text: `Enterprise Level with Robust Feature Sets` },
  ] satisfies Stat[],
  filters: [`All`, `Featured`, `PWA`, `Website`, `WordPress`, `E-Commerce`, `Game`, `API`],
  services: [
    { icon: `fa-solid fa-layer-group`, title: `Front-End Systems`, text: `Responsive HTML, CSS, Sass, JavaScript, TypeScript, app shells, design systems, and polished UI states.` },
    { icon: `fa-solid fa-database`, title: `Back-End + Data`, text: `Python, JSON, SQL, REST APIs, Firebase, WordPress/MySQL, automation, and practical integration work.` },
    { icon: `fa-solid fa-cart-shopping`, title: `CMS + Commerce`, text: `WordPress restorations, Shopify ideas, Squarespace support, branded pages, portfolio pieces, and content workflows.` },
  ] satisfies Service[],
  skills: [
    { label: `HTML`, group: `Markup`, icon: `fa-brands fa-html5` },
    { label: `CSS`, group: `Style`, icon: `fa-brands fa-css3-alt` },
    { label: `Sass`, group: `Style`, icon: `fa-brands fa-sass` },
    { label: `JavaScript`, group: `Logic`, icon: `fa-brands fa-js` },
    { label: `TypeScript`, group: `Logic`, icon: `fa-solid fa-code` },
    { label: `React`, group: `UI`, icon: `fa-brands fa-react` },
    { label: `Next`, group: `UI`, icon: `fa-solid fa-n` },
    { label: `Angular`, group: `UI`, icon: `fa-brands fa-angular` },
    { label: `Node`, group: `Runtime`, icon: `fa-brands fa-node-js` },
    { label: `Python`, group: `Backend`, icon: `fa-brands fa-python` },
    { label: `SQL`, group: `Data`, icon: `fa-solid fa-database` },
    { label: `JSON`, group: `Data`, icon: `fa-solid fa-file-code` },
    { label: `Firebase`, group: `BaaS`, icon: `fa-solid fa-fire-flame-curved` },
    { label: `WordPress`, group: `CMS`, icon: `fa-brands fa-wordpress` },
    { label: `Shopify`, group: `Commerce`, icon: `fa-brands fa-shopify` },
    { label: `GitHub`, group: `Code`, icon: `fa-brands fa-github` },
    { label: `PWA`, group: `App`, icon: `fa-solid fa-mobile-screen-button` },
  ] satisfies Skill[],
  capabilities: [`Python`, `JSON`, `SQL`, `REST`, `Firebase`, `WordPress`, `Shopify`, `Auth`, `PWA`, `Sass`, `TypeScript`, `Responsive UI`],
  gallery: [`Dashboards`, `WordPress`, `PWA Shells`, `Data Apps`, `Design Studies`, `Game UI`],
  social: [
    { label: `GitHub`, href: `https://github.com/strawhat19`, icon: `fa-brands fa-github` },
    { label: `LinkedIn`, href: `https://www.linkedin.com/in/rakib-ahmed19/`, icon: `fa-brands fa-linkedin` },
    { label: `Piratechs`, href: `https://piratechs.com/`, icon: `fa-solid fa-globe` },
  ] satisfies SocialLink[],
};
