import type { NavItem, PageCopy, Project, Service, Skill, SocialLink, Stat, TopBarItem } from '@/shared/types/site';

export const siteConfig = {
  title: `Piratechs`,
  domain: `piratechs.com`,
  contactEmail: `info@piratechs.com`,
  description: `Full-stack software portfolio and digital studio with a front-end focus.`,
  logo: {
    dark: `/assets/piratechs/svg/Piratechs-Icon-White.svg`,
    light: `/assets/piratechs/svg/Piratechs-Icon-Navy.svg`,
    tile: `/assets/piratechs/images/Piratechs-Icon-App-Tile-Navy-BG.png`,
  },
  nav: [
    { id: `home`, label: `Home`, href: `/`, icon: `fa-solid fa-house` },
    { id: `about`, label: `About`, href: `/about`, icon: `fa-solid fa-anchor` },
    { id: `projects`, label: `Projects`, href: `/projects`, icon: `fa-solid fa-diagram-project` },
    { id: `services`, label: `Services`, href: `/services`, icon: `fa-solid fa-screwdriver-wrench` },
    { id: `store`, label: `Store`, href: `/store`, icon: `fa-solid fa-store` },
    { id: `features`, label: `Features`, href: `/features`, icon: `fa-solid fa-list-check` },
    { id: `gallery`, label: `Gallery`, href: `/gallery`, icon: `fa-solid fa-images` },
    { id: `contact`, label: `Contact`, href: `/contact`, icon: `fa-solid fa-paper-plane` },
  ] satisfies NavItem[],
  topBarItems: [
    { icon: `fa-solid fa-code`, label: `Stack`, text: `TypeScript + Sass + Next.js` },
    { icon: `fa-solid fa-database`, label: `Data`, text: `Python, JSON, SQL, and REST APIs` },
    { icon: `fa-solid fa-briefcase`, label: `Experience`, text: `4+ years software engineering at Mitsubishi Electric` },
    { icon: `fa-solid fa-mobile-screen-button`, label: `PWA`, text: `Responsive web and installable app direction` },
    { icon: `fa-brands fa-wordpress`, label: `CMS`, text: `WordPress restorations, CMS builds, and portfolio sites` },
    { icon: `fa-brands fa-github`, label: `Projects`, text: `Live deployments and source-backed proof of work` },
    { icon: `fa-solid fa-fire-flame-curved`, label: `Firebase`, text: `Auth-ready app shell for future database features` },
    { icon: `fa-solid fa-screwdriver-wrench`, label: `Services`, text: `Front-end polish backed by full-stack delivery` },
  ] satisfies TopBarItem[],
  pages: {
    home: {
      eyebrow: `Piratechs`,
      title: `Design & Develop Full-Stack Applications`,
      summary: `Built with Next.js App Router + API, TypeScript, SASS, Firebase, Firestore, Authentication, Cloud Functions, MUI, React, SVG`,
    },
    about: {
      eyebrow: `About`,
      title: `A brand-first portfolio for serious software craft`,
      summary: `Built around the Piratechs identity, this site focuses on technical range, product thinking, and the UI polish that makes complex systems easier to use.`,
    },
    projects: {
      eyebrow: `Projects`,
      title: `Projects that prove the stack`,
      summary: `A growing archive of web apps, WordPress restorations, dashboards, data tools, game-adjacent builds, and experiments with live links and source references.`,
    },
    services: {
      eyebrow: `Services`,
      title: `From landing pages to full-stack products`,
      summary: `Responsive front ends, data-driven apps, CMS builds, automation, integrations, and branded product systems with practical delivery in mind.`,
    },
    store: {
      eyebrow: `Store`,
      title: `A future shelf for digital tools`,
      summary: `A scalable route for templates, small utilities, downloadable assets, and productized Piratechs experiments when the app grows past portfolio mode.`,
    },
    features: {
      eyebrow: `Features`,
      title: `Fast, installable, responsive, and easy to expand`,
      summary: `The Next foundation gives Piratechs clean routes, PWA behavior, reusable sections, API routes, and a future Firebase-backed data layer.`,
    },
    gallery: {
      eyebrow: `Gallery`,
      title: `A visual archive for apps, brands, and experiments`,
      summary: `A showcase route for screenshots, logos, WordPress work, interface studies, game projects, and future portfolio media.`,
    },
    contact: {
      eyebrow: `Contact`,
      title: `Let Piratechs build the next version`,
      summary: `A focused contact route for portfolio reviewers, collaborators, recruiters, and future clients looking for front-end polish backed by full-stack depth.`,
    },
  } satisfies Record<string, PageCopy>,
  stats: [
    { label: `Years of Experience`, value: `10+`, text: `Full Stack Design // Development` },
    { label: `Technologies`, value: `100+`, text:  `PWAs, Websites, E-Commerce, Games, APIs` },
    { label: `Applications`, value: `1000+`, text: `Enterprise Level with Robust Feature Sets` },
  ] satisfies Stat[],
  filters: [`Featured`, `All`, `PWA`, `Website`, `WordPress`, `E-Commerce`, `Game`, `API`],
  projects: [
    {
      type: `PWA`,
      status: `Live`,
      featured: true,
      id: `productivf`,
      title: `ProductivF`,
      liveUrl: `https://www.productivf.com/`,
      tech: [`TypeScript`, `Sass`, `Auth`, `Data UI`],
      summary: `Dashboard-style productivity app with auth, grids, records, and app-shell navigation patterns.`,
    },
    {
      featured: true,
      status: `Live`,
      id: `dyer-posta`,
      title: `Dyer & Posta`,
      type: `WordPress`,
      liveUrl: `https://dyerposta.com/`,
      tech: [`WordPress`, `PHP`, `MySQL`, `CSS`],
      summary: `Elegant salon portfolio restoration with responsive layout, classic WordPress editing, and refined carousel behavior.`,
    },
    {
      id: `mydex`,
      type: `API`,
      status: `Live`,
      featured: true,
      title: `MyDex Pokedex`,
      liveUrl: `https://mydex-pokedex.com/`,
      tech: [`PHP`, `Sass`, `Firebase`, `API`],
      codeUrl: `https://github.com/strawhat19/MyDex-Pokedex-Clone`,
      summary: `Pokedex clone with accounts, saved teams, profile concepts, API data, PHP templating, Sass, and Firebase.`,
    },
    {
      type: `PWA`,
      featured: true,
      status: `Live`,
      id: `piratechs-pwa`,
      title: `Piratechs Next PWA`,
      tech: [`Next.js`, `PWA`, `TypeScript`, `Sass`],
      liveUrl: `https://piratechs-next-pwa-template-2025.vercel.app/`,
      codeUrl: `https://github.com/strawhat19/Piratechs-Next-PWA-Template-2025`,
      summary: `Reusable app-shell template with PWA direction, settings, navigation, and installable app thinking.`,
    },
    {
      type: `PWA`,
      status: `Live`,
      featured: true,
      id: `smasherscape`,
      title: `Smasherscape`,
      liveUrl: `https://smasherscape.vercel.app/`,
      tech: [`Next.js`, `Firebase`, `Sass`, `Admin`],
      codeUrl: `https://github.com/strawhat19/Smasherscape`,
      summary: `Game-flavored leaderboard and admin tooling with searchable player stats and custom UI identity.`,
    },
    {
      type: `API`,
      id: `geodata`,
      status: `Live`,
      featured: true,
      title: `GeoData`,
      liveUrl: `https://strawhat19.github.io/GeoData/`,
      codeUrl: `https://github.com/strawhat19/GeoData`,
      tech: [`JavaScript`, `JSON`, `Maps`, `Weather API`],
      summary: `Location, timezone, weather, maps, and API-driven data visualization work in a compact interface.`,
    },
    {
      status: `Live`,
      type: `E-Commerce`,
      id: `creative-workshop`,
      title: `Creative Workshop`,
      liveUrl: `https://creative-workshop.vercel.app/`,
      tech: [`Next.js`, `Shopify`, `Firebase`, `WebSockets`],
      codeUrl: `https://github.com/strawhat19/CreativeWorkshop`,
      summary: `Commerce and creative studio concept with product management, auth patterns, Shopify thinking, and live UI controls.`,
    },
    {
      status: `Live`,
      type: `Website`,
      id: `design-development`,
      title: `Design Development`,
      tech: [`HTML`, `Sass`, `TypeScript`, `Motion`],
      liveUrl: `https://strawhat19.github.io/Design-Development/`,
      codeUrl: `https://github.com/strawhat19/Design-Development`,
      summary: `Early design/code lab exploring page state, animation, Sass, TypeScript, PHP, jQuery, and interaction patterns.`,
    },
    {
      type: `Game`,
      id: `sanctuary`,
      title: `Sanctuary`,
      tech: [`C#`, `Unity`],
      status: `Development`,
      codeUrl: `https://github.com/strawhat19/Sanctuary`,
      summary: `A forest-fire prevention game built with C# and Unity that won 2nd place in the 2020 Global Game Jam.`,
    },
  ] satisfies Project[],
  services: [
    { icon: `fa-solid fa-layer-group`, title: `Front-End Systems`, text: `Responsive HTML, CSS, Sass, JavaScript, TypeScript, app shells, design systems, and polished UI states.` },
    { icon: `fa-solid fa-database`, title: `Back-End + Data`, text: `Python, JSON, SQL, REST APIs, Firebase, WordPress/MySQL, automation, and practical integration work.` },
    { icon: `fa-solid fa-cart-shopping`, title: `CMS + Commerce`, text: `WordPress restorations, Shopify ideas, Squarespace support, branded pages, portfolio pieces, and content workflows.` },
  ] satisfies Service[],
  skills: [
    { label: `HTML`, group: `Markup`, icon: `fa-brands fa-html5` },
    { label: `CSS`, group: `Style`, icon: `fa-brands fa-css3-alt` },
    { label: `Sass`, group: `Style`, icon: `fa-brands fa-sass` },
    { label: `JavaScript`, group: `Logic`, icon: `fa-brands fa-js` },
    { label: `TypeScript`, group: `Logic`, icon: `fa-solid fa-code` },
    { label: `React`, group: `UI`, icon: `fa-brands fa-react` },
    { label: `Next.js`, group: `UI`, icon: `fa-solid fa-n` },
    { label: `Angular`, group: `UI`, icon: `fa-brands fa-angular` },
    { label: `Node`, group: `Runtime`, icon: `fa-brands fa-node-js` },
    { label: `Python`, group: `Backend`, icon: `fa-brands fa-python` },
    { label: `SQL`, group: `Data`, icon: `fa-solid fa-database` },
    { label: `JSON`, group: `Data`, icon: `fa-solid fa-file-code` },
    { label: `Firebase`, group: `BaaS`, icon: `fa-solid fa-fire-flame-curved` },
    { label: `WordPress`, group: `CMS`, icon: `fa-brands fa-wordpress` },
    { label: `Shopify`, group: `Commerce`, icon: `fa-brands fa-shopify` },
    { label: `GitHub`, group: `Code`, icon: `fa-brands fa-github` },
    { label: `PWA`, group: `App`, icon: `fa-solid fa-mobile-screen-button` },
  ] satisfies Skill[],
  capabilities: [`Python`, `JSON`, `SQL`, `REST`, `Firebase`, `WordPress`, `Shopify`, `Auth`, `PWA`, `Sass`, `TypeScript`, `Responsive UI`],
  gallery: [`Dashboards`, `WordPress`, `PWA Shells`, `Data Apps`, `Design Studies`, `Game UI`],
  social: [
    { label: `GitHub`, href: `https://github.com/strawhat19`, icon: `fa-brands fa-github` },
    { label: `LinkedIn`, href: `https://www.linkedin.com/`, icon: `fa-brands fa-linkedin` },
    { label: `Piratechs`, href: `https://piratechs.com/`, icon: `fa-solid fa-globe` },
  ] satisfies SocialLink[],
};
